---
title: "e2"
format: html
---

Factors
Regular expressions
Characters: detect, replace, extract certain patterns
Characters to factors: relabel or reorder a character variable

fct_relevel() to store character as factor, making values actual levels
fct_reorder() to reorder levels

Strings
To detect, replace or extract certain patterns in character strings
str_replace(x, pattern, replacement) finds the first part of x that matches the pattern and replaces it with replacement
str_replace_all(x, pattern, replacement) finds all instances in x that matches the pattern and replaces it with replacement
str_to_lower(x) converts all upper case letters in x to lower case
str_sub(x, start, end) only keeps a subset of characters in x, from start (a number indexing the first letter to keep) to end (a number indexing the last letter to keep)
str_length(x) records the number of characters in x
str_detect(x, pattern) is TRUE if x contains the given pattern and FALSE otherwise

separate() to split a column into 2 new columns


Data Import
Data projects starts with: 
1. Data collection: finding, saving, importing
2. Analysis: EDA - getting to know and refine our data

.csv: comma separated values

read_csv(): save excel and google sheets files as csv
read_delim(): delimited formats (tab,space,etc.)
read_sheet(): google sheet
st_read(): spatial data shape file

Absolute: specific location
Relative: relative to where the file is read

